# Generated by Django 6.0.2 on 2026-02-26 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='petition_id',
            new_name='petition',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('petition', 'user')},
        ),
    ]
