# Generated by Django 6.0.2 on 2026-02-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
