# Generated by Django 6.0.2 on 2026-02-17 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, max_length=500)),
                ('about', models.TextField(blank=True, max_length=500)),
                ('icon', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('major', models.CharField(choices=[('CS', 'Computer Science'), ('RO', 'Robotics'), ('DA', 'IT and Decision Analytics')], default='CS', max_length=2)),
                ('year_of_study', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], default=1, verbose_name='Current Course Year')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
