# Generated by Django 6.0.2 on 2026-02-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answear',
            new_name='answer',
        ),
    ]
