# Generated by Django 6.0.2 on 2026-02-21 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.AddField(
            model_name='material',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='activity_materials/'),
        ),
        migrations.AddField(
            model_name='material',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
