# Generated by Django 6.0.2 on 2026-02-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_material_quantity_material_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='courses_pics/default.jpg', upload_to='courses_pics/'),
        ),
    ]
