# Generated by Django 6.0.2 on 2026-02-22 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=500)),
                ('icon', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('major', models.CharField(choices=[('CS', "Комп'ютерні науки"), ('RO', 'Робототехніка'), ('DA', 'ІТ та Аналітика Рішень')], default='NONE', max_length=2)),
                ('year_of_study', models.IntegerField(choices=[(1, 'Перший курс'), (2, 'Другий курс'), (3, 'Третій курс'), (4, 'Четвертий курс')], default=0, verbose_name='Current Course Year')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
