# Generated by Django 6.0.2 on 2026-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(choices=[('CS', "Комп'ютерні Науки"), ('RO', 'Робототехніка'), ('DA', 'ІТ та Аналітика Рішень')], default='NONE', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, 'перший курс'), (2, 'другий курс'), (3, 'третій курс'), (4, 'четвертий курс')], default=0, verbose_name='Current Course Year'),
        ),
    ]
